use MyHomeCatch;
CREATE TABLE APPLYHOME_APT (
                            PBLANC_NO                      VARCHAR(20)    PRIMARY KEY,
                            BSNS_MBY_NM                    VARCHAR(100)   NOT NULL,
                            CNSTRCT_ENTRPS_NM              VARCHAR(100)   NOT NULL,
                            CNTRCT_CNCLS_BGNDE             DATE           NOT NULL,
                            CNTRCT_CNCLS_ENDDE             DATE           NOT NULL,
                            GNRL_RNK1_CRSPAREA_ENDDE       DATE           NOT NULL,
                            GNRL_RNK1_CRSPAREA_RCPTDE      DATE           NOT NULL,
                            GNRL_RNK1_ETC_AREA_ENDDE       DATE           NOT NULL,
                            GNRL_RNK1_ETC_AREA_RCPTDE      DATE           NOT NULL,
                            GNRL_RNK1_ETC_GG_ENDDE         DATE           NULL,
                            GNRL_RNK1_ETC_GG_RCPTDE        DATE           NULL,
                            GNRL_RNK2_CRSPAREA_ENDDE       DATE           NOT NULL,
                            GNRL_RNK2_CRSPAREA_RCPTDE      DATE           NOT NULL,
                            GNRL_RNK2_ETC_AREA_ENDDE       DATE           NOT NULL,
                            GNRL_RNK2_ETC_AREA_RCPTDE      DATE           NOT NULL,
                            GNRL_RNK2_ETC_GG_ENDDE         DATE           NULL,
                            GNRL_RNK2_ETC_GG_RCPTDE        DATE           NULL,
                            HMPG_ADRES                     VARCHAR(200)   NULL,
                            HOUSE_DTL_SECD                 CHAR(2)        NOT NULL,
                            HOUSE_DTL_SECD_NM              VARCHAR(50)    NOT NULL,
                            HOUSE_MANAGE_NO                VARCHAR(20)    NOT NULL,
                            HOUSE_NM                       VARCHAR(100)   NOT NULL,
                            HOUSE_SECD                     CHAR(2)        NOT NULL,
                            HOUSE_SECD_NM                  VARCHAR(50)    NOT NULL,
                            HSSPLY_ADRES                   VARCHAR(200)   NULL,
                            HSSPLY_ZIP                     VARCHAR(10)    NULL,
                            IMPRMN_BSNS_AT                 CHAR(1)        NOT NULL,
                            LRSCL_BLDLND_AT                CHAR(1)        NOT NULL,
                            MDAT_TRGET_AREA_SECD           CHAR(1)        NOT NULL,
                            MDHS_TELNO                     VARCHAR(20)    NULL,
                            MVN_PREARNGE_YM                CHAR(6)        NULL,
                            NPLN_PRVOPR_PUBLIC_HOUSE_AT    CHAR(1)        NOT NULL,
                            NSPR_C_NM                      VARCHAR(50)    NULL,
                            PBLANC_URL                     VARCHAR(300)   NULL,
                            PRZWNER_PRESNATN_DE            DATE           NULL,
                            PUBLIC_HOUSE_EARTH_AT          CHAR(1)        NOT NULL,
                            PUBLIC_HOUSE_SPCLW_APPLC_AT    CHAR(1)        NOT NULL,
                            RCEPT_BGNDE                    DATE           NOT NULL,
                            RCEPT_ENDDE                    DATE           NOT NULL,
                            RCRIT_PBLANC_DE                DATE           NOT NULL,
                            RENT_SECD                      CHAR(1)        NOT NULL,
                            RENT_SECD_NM                   VARCHAR(50)    NOT NULL,
                            SPECLT_RDN_EARTH_AT            CHAR(1)        NOT NULL,
                            SPSPLY_RCEPT_BGNDE             DATE           NULL,
                            SPSPLY_RCEPT_ENDDE             DATE           NULL,
                            SUBSCRPT_AREA_CODE             VARCHAR(10)    NOT NULL,
                            SUBSCRPT_AREA_CODE_NM          VARCHAR(50)    NOT NULL,
                            TOT_SUPLY_HSHLDCO              INT            NOT NULL
);